language: python
codecov: true

services:
  - docker

before_install:
  - docker build -t assignment2/app .

script:
  - docker run assignment2/app coverage run ./app/src/unittest.py

after_script:
  - docker run assignment2/app codecov