services:
  - docker

before_install:
  - docker build -t assignment2/app .

script:
  - mkdir shared
  - docker run -v "$PWD/shared:/shared" assignment2/app /bin/sh -c "coverage run -m unittest app.src.unittest; mv .coverage shared"
  - mv shared/.coverage .

after_script:
  - codecov