language: python
cache: pip

services:
  - docker

before_install:
  - docker build -t assignment2/app .

script:
  - mkdir shared
  - docker run -v "$PWD/shared:/shared" assignment2/app /bin/sh -c "coverage run -m unittest app.src.unittest; coverage xml; mv coverage.xml shared"
  - mv shared/coverage.xml .

after_script:
  - codecov